# https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md

[[constraint]]
  branch = "master"
  name = "github.com/codahale/hdrhistogram"

[[constraint]]
  branch = "master"
  name = "github.com/edsrzf/mmap-go"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
