// Code generated by "stringer --type=Unit"; DO NOT EDIT

package mmvdump

import "fmt"

const _Unit_name = "OneUnitNanosecondUnitMicrosecondUnitMillisecondUnitSecondUnitMinuteUnitHourUnitByteUnitKilobyteUnitMegabyteUnitGigabyteUnitTerabyteUnitPetabyteUnitExabyteUnit"

var _Unit_map = map[Unit]string{
	1048576:   _Unit_name[0:7],
	16777216:  _Unit_name[7:21],
	16781312:  _Unit_name[21:36],
	16785408:  _Unit_name[36:51],
	16789504:  _Unit_name[51:61],
	16793600:  _Unit_name[61:71],
	16797696:  _Unit_name[71:79],
	268435456: _Unit_name[79:87],
	268500992: _Unit_name[87:99],
	268566528: _Unit_name[99:111],
	268632064: _Unit_name[111:123],
	268697600: _Unit_name[123:135],
	268763136: _Unit_name[135:147],
	268828672: _Unit_name[147:158],
}

func (i Unit) String() string {
	if str, ok := _Unit_map[i]; ok {
		return str
	}
	return fmt.Sprintf("Unit(%d)", i)
}
